---
title: "PHQ4"
format: revealjs
editor: visual
---

## Read Data

```{r}
library(readr)
library(tidyverse)

datadf     <- read_csv("Dataset2020_2024_PHQ4_Rashomon.csv")

datadf     <- datadf |>
  mutate(date_parsed     = as.POSIXct(date_modified, format = "%m/%d/%Y %I:%M:%S %p"),
         weekday_weekend = ifelse(weekdays(date_parsed) %in% c("Saturday", "Sunday"), "Weekend", "Weekday"),
         hour_numeric    = as.numeric(format(date_parsed, "%H")) + as.numeric(format(date_parsed, "%M")) / 60)

datadf     <- datadf[datadf$sex != "Other",]
datadf$sex <- factor(datadf$sex)
```

## Plot data

```{r}
library(ggplot2)

ggplot(datadf, aes(age, PHQ4_score, color=education, shape=sex)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~sex)

hist(datadf$PHQ4_score)
```

## Do model

```{r}
library(DALEX)
library(randomForest)
library(modelStudio)

model <- randomForest(PHQ2_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$PHQ2_score)

p1 <- plot(model_profile(modelex, variables = "age", groups = "weekday_weekend")) + ggtitle("PHQ2") + 
  geom_rug(sides = "b") 
p1
```

```{r}
model <- randomForest(GAD2_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$GAD2_score)

p2 <- plot(model_profile(modelex, variables = "age", groups = "weekday_weekend")) + ggtitle("GAD2") + 
  geom_rug(sides = "b") 
p2
```

```{r}
model <- randomForest(PHQ4_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$PHQ4_score)

p3 <- plot(model_profile(modelex, variables = "age", groups = "sex")) + ggtitle("PHQ4") + 
  geom_rug(sides = "b") 
p3
```

```{r}
p4 <- plot(model_profile(modelex, variables = "age", groups = "weekday_weekend")) + ggtitle("PHQ4") + 
  geom_rug(sides = "b") 
p4
```
```{r}
p5 <- plot(model_profile(modelex, variables = "hour_numeric")) + 
  ggtitle("PHQ4") + 
  geom_rug(sides = "b") 
p5
```

```{r}
library(patchwork)
p1 + p2 + p3 + p4
```



```{r}
library(DALEX)
library(randomForest)
library(modelStudio)

model <- randomForest(PHQ2_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$PHQ2_score)

p1 <- plot(model_profile(modelex, variables = "age", groups = "sex")) + ggtitle("PHQ2")

model <- randomForest(GAD2_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$GAD2_score)

p2 <- plot(model_profile(modelex, variables = "age", groups = "sex")) + ggtitle("GAD2")


model <- randomForest(PHQ4_score ~ age + education + sex + weekday_weekend + hour_numeric, data = datadf)
modelex <- explain(model, data = datadf[,c(8, 9, 10, 11, 15, 16)], y = datadf$PHQ4_score)

p3 <- plot(model_profile(modelex, variables = "age", groups = "sex")) + ggtitle("PHQ4")

library(patchwork)
p1 + p2 + p3

plot(model_profile(modelex, variables = "age", N = NULL) , 
     geom = "profiles")

mp <- model_profile(modelex, variables = "age", N = NULL)
mp <- model_profile(modelex, variable_splits = list(age = 18:80), N = NULL)

mp_s <- model_profile(modelex, groups = "sex", variable_splits = list(age = 18:80), N = NULL)
mp_e <- model_profile(modelex, groups = "education", variable_splits = list(age = 18:80), N = NULL)

plot(model_profile(modelex, variables = "age", groups = "sex")) + ggtitle("GAD2_score")

plot(model_profile(modelex, variables = "age", groups = "education", N = 700) , 
     geom = "profiles")


ms <- modelStudio(modelex)

```

## Do bootstrap

```{r}
N <- 10
n <- nrow(datadf)

ndf <- list()
models <- list()
explainers <- list()
profiles <- list()
profiles_s <- list()
profiles_e <- list()
profiles_w <- list()

for (i in 1:N) {
  ndf[[i]] <- datadf[sample(1:n, n, replace = TRUE),]
  models[[i]] <- randomForest(PHQ4_score ~ age+education+sex+weekday_weekend+hour_numeric,
                              data=ndf[[i]])
  explainers[[i]] <- DALEX::explain(models[[i]], 
                             data = ndf[[i]][,c(8,9,10,11,15,16)], 
                             y = ndf[[i]]$PHQ4_score, verbose = FALSE)
  profiles[[i]] <- model_profile(explainers[[i]], 
                                 variable_splits = list(age=18:80), 
                                 N=NULL)
  profiles_s[[i]] <- model_profile(explainers[[i]], groups = "sex", 
                                 variable_splits = list(age=18:80), 
                                 N=NULL)
  profiles_e[[i]] <- model_profile(explainers[[i]], groups = "education", 
                                 variable_splits = list(age=18:80), 
                                 N=NULL)
  profiles_w[[i]] <- model_profile(explainers[[i]], groups = "weekday_weekend", 
                                 variable_splits = list(age=18:80), 
                                 N=NULL)

  cat(i,"\n")
}


tmp <- lapply(1:length(profiles), function(i) data.frame(profiles[[i]]$agr_profiles, idx = i))
all_profiles <- do.call(rbind, tmp)

tmp_s <- lapply(1:length(profiles), function(i) data.frame(profiles_s[[i]]$agr_profiles, idx = i))
all_profiles_s <- do.call(rbind, tmp_s)

tmp_e <- lapply(1:length(profiles), function(i) data.frame(profiles_e[[i]]$agr_profiles, idx = i))
all_profiles_e <- do.call(rbind, tmp_e)

library(dplyr)
all_profiles_e |> 
  group_by(`X_x_`, `X_groups_`) |>
  summarise(x = mean(`X_x_`),
            min = min(`X_yhat_`),
            q025 = quantile(`X_yhat_`, 0.025),
            q975 = quantile(`X_yhat_`, 0.975),
            max = max(`X_yhat_`),
            avg = mean(`X_yhat_`),
            sd = sd(`X_yhat_`)) -> ribbons_e

all_profiles_s |> 
  group_by(`X_x_`, `X_groups_`) |>
  summarise(x = mean(`X_x_`),
            min = min(`X_yhat_`),
            q025 = quantile(`X_yhat_`, 0.025),
            q975 = quantile(`X_yhat_`, 0.975),
            max = max(`X_yhat_`),
            avg = mean(`X_yhat_`),
            sd = sd(`X_yhat_`)) -> ribbons_s


ribbons <- data.frame(min = tapply(all_profiles$`X_yhat_`, all_profiles$`X_x_`, min),
                      max = tapply(all_profiles$`X_yhat_`, all_profiles$`X_x_`, max),
                      sd = tapply(all_profiles$`X_yhat_`, all_profiles$`X_x_`, sd),
                      avg = tapply(all_profiles$`X_yhat_`, all_profiles$`X_x_`, mean))
ribbons$x <- as.numeric(rownames(ribbons))


ggplot(all_profiles, aes(X_x_, X_yhat_)) +
    geom_ribbon(data = ribbons_e, aes(ymin = q025, ymax = q975, y = avg, x = x, fill = factor(X_groups_)), alpha = 0.2) +
    geom_line(data = ribbons_e, aes(y = avg, x = x, color = factor(X_groups_))) +
    theme_bw() +
    xlab("Age") +
    ylab("Partial Dependence") +
    scale_fill_discrete("Education") +
    scale_color_discrete("Education") +
    ggtitle("Percentile Bootstrap Intervals for Random Forest PD profiles", "500 replications, CI alpha=0.05")

ggplot(all_profiles, aes(X_x_, X_yhat_))+
  geom_ribbon(data=ribbons_s, aes(ymin=q025, ymax=q975, y=avg, x=x, fill=`X_groups_`), alpha=0.2)+
  geom_line(data=ribbons_s, aes(y=avg, x=x, color=`X_groups_`)) +
  theme_bw() + xlab("Age") + ylab("Partial Dependence") +
  scale_fill_discrete("Sex") +
  scale_color_discrete("Sex") +ggtitle("Percentile Bootstrap Intervals for Random Forest PD profiles", "500 replications, CI alpha=0.05")

ggplot(all_profiles, aes(X_x_, X_yhat_)) +
  geom_ribbon(data = ribbons_e, aes(ymin = q025, ymax = q975, y = avg, x = x, fill = factor(X_groups_)), alpha = 0.2) +
  geom_line(data = ribbons_e, aes(y = avg, x = x, color = factor(X_groups_))) +
  theme_bw() +
  xlab("Age") +
  ylab("Partial Dependence") +
  scale_fill_discrete(name = "Education") +
  scale_color_discrete(name = "Education") +
  ggtitle(
    "Percentile Bootstrap Intervals (alpha=0.05) for Random Forest PD profiles", 
    subtitle = "500 replications, light blue - min/max, darker blue - avg±2*sd"
  )

#ggplot(all_profiles, aes(X_x_, X_yhat_))+
#  geom_line(aes(group=idx), alpha=0.1) +
#  geom_ribbon(data=ribbons, aes(ymin=min, ymax=max, y=max, x=x), fill="blue", #alpha=0.1) +
#  geom_ribbon(data=ribbons, aes(ymin=avg-2*sd, ymax=avg+2*sd, y=avg, x=x), fill="blue", alpha=0.2) +
#  geom_smooth() +
#  theme_bw() + xlab("Age") + ylab("Partial Dependence") + ggtitle("Bootstrap Intervals for Random Forest", "500 replications, light blue - min/max, darker blue - avg+- 2*sd") +
#  geom_line(data = mp$agr_profiles, aes(`_x_`, `_yhat_`), color = "blue", size=2)
```


```{r}

```

